### ISSUE TITLE
Checklist for v1-2

### ISSUE THREAD

**Issue by bpbond** [COMPASS-DOE/sensor-data-pipeline#220]
Looking ahead to January

- [x] Data update through end of 2024
- [x] #219 
- [x] #209 
- [x] #204 
- [x] #226 
- [x] #214 
- [x] #217 
- [x] #210

**Comment by bpbond** [comment]
We also need to decide how we'll run the v1-2 release. Options:

- [ ] BBL handles data updating and troubleshooting, updates metadata and READMEs, generates `v1-2`, and SP checks everything (this is basically what we did for `v1-0` and `v1-1`)
- [ ] BBL handles data updating and troubleshooting; SP updates metadata and READMEs and generates `v1-2`; both check
- [ ] SP handles everything, with BBL on call as needed
- [ ] Other?

**Comment by bpbond** [comment]
@stephpenn1 Here ☝️ is the comment and question to you I mentioned yesterday. Thanks!

**Comment by stephpenn1** [comment]
Let's do the first option based on our timeline, but if possible I would like to shadow the data updating and metadata edits. Maybe on a teams call?

**Comment by bpbond** [comment]
OK, sounds good, including maybe a teams shadow session. Thanks.

**Comment by stephpenn1** [comment]
Great, that way I can do the next one!
